
insert into flow.protocols (protocol) values 

('{ "ipprotocolname": "HOPOPT", "ipprotocolnumber": "0", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2460]"}'),
('{ "ipprotocolname": "ICMP", "ipprotocolnumber": "1", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC792]"}'),
('{ "ipprotocolname": "IGMP", "ipprotocolnumber": "2", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC1112]"}'),
('{ "ipprotocolname": "GGP", "ipprotocolnumber": "3", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC823]"}'),
('{ "ipprotocolname": "IPv4", "ipprotocolnumber": "4", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2003]"}'),
('{ "ipprotocolname": "ST", "ipprotocolnumber": "5", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC1190][RFC1819]"}'),
('{ "ipprotocolname": "TCP", "ipprotocolnumber": "6", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC793]"}'),
('{ "ipprotocolname": "CBT", "ipprotocolnumber": "7", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Tony_Ballardie]"}'),
('{ "ipprotocolname": "EGP", "ipprotocolnumber": "8", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC888][David_Mills]"}'),
('{ "ipprotocolname": "IGP", "ipprotocolnumber": "9", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "BBN-RCC-MON", "ipprotocolnumber": "10", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steve_Chipman]"}'),
('{ "ipprotocolname": "NVP-II", "ipprotocolnumber": "11", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC741][Steve_Casner]"}'),
('{ "ipprotocolname": "PUP", "ipprotocolnumber": "12", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[Boggs  D.  J. Shoch  E. Taft  and R. Metcalfe  ''PUP: An Internetwork Architecture''  XEROX Palo Alto Research Center  CSL-79-10  July 1979  also in IEEE Transactions on Communication  Volume COM-28  Number 4  April 1980.][[XEROX]]''"}'),
('{ "ipprotocolname": "ARGUS (deprecated)", "ipprotocolnumber": "13", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Robert_W_Scheifler]"}'),
('{ "ipprotocolname": "EMCON", "ipprotocolnumber": "14", "servicename": "", "portnumber": "", "type": "protocol", "description": "[<mystery contact>]"}'),
('{ "ipprotocolname": "XNET", "ipprotocolnumber": "15", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[Haverty  J.  ''XNET Formats for Internet Protocol Version 4''  IEN 158  October 1980.][Jack_Haverty]''"}'),
('{ "ipprotocolname": "CHAOS", "ipprotocolnumber": "16", "servicename": "", "portnumber": "", "type": "protocol", "description": "[J_Noel_Chiappa]"}'),
('{ "ipprotocolname": "UDP", "ipprotocolnumber": "17", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC768][Jon_Postel]"}'),
('{ "ipprotocolname": "MUX", "ipprotocolnumber": "18", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[Cohen  D. and J. Postel  ''Multiplexing Protocol''  IEN 90  USC/Information Sciences Institute  May 1979.][Jon_Postel]''"}'),
('{ "ipprotocolname": "DCN-MEAS", "ipprotocolnumber": "19", "servicename": "", "portnumber": "", "type": "protocol", "description": "[David_Mills]"}'),
('{ "ipprotocolname": "HMP", "ipprotocolnumber": "20", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC869][Bob_Hinden]"}'),
('{ "ipprotocolname": "PRM", "ipprotocolnumber": "21", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Zaw_Sing_Su]"}'),
('{ "ipprotocolname": "XNS-IDP", "ipprotocolnumber": "22", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[''The Ethernet  A Local Area Network: Data Link Layer and Physical Layer Specification''  AA-K759B-TK  Digital Equipment Corporation  Maynard  MA.  Also as: ''The Ethernet - A Local Area Network''  Version 1.0  Digital Equipment Corporation  Intel Corporation  Xerox Corporation  September 1980.  And: ''The Ethernet  A Local Area Network: Data Link Layer and Physical Layer Specifications''  Digital  Intel and Xerox  November 1982.  And: XEROX  ''The Ethernet  A Local Area Network: Data Link Layer and Physical Layer Specification''  X3T51/80-50  Xerox Corporation  Stamford  CT.  October 1980.][[XEROX]]''"}'),
('{ "ipprotocolname": "TRUNK-1", "ipprotocolnumber": "23", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Barry_Boehm]"}'),
('{ "ipprotocolname": "TRUNK-2", "ipprotocolnumber": "24", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Barry_Boehm]"}'),
('{ "ipprotocolname": "LEAF-1", "ipprotocolnumber": "25", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Barry_Boehm]"}'),
('{ "ipprotocolname": "LEAF-2", "ipprotocolnumber": "26", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Barry_Boehm]"}'),
('{ "ipprotocolname": "RDP", "ipprotocolnumber": "27", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC908][Bob_Hinden]"}'),
('{ "ipprotocolname": "IRTP", "ipprotocolnumber": "28", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC938][Trudy_Miller]"}'),
('{ "ipprotocolname": "ISO-TP4", "ipprotocolnumber": "29", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC905][<mystery contact>]"}'),
('{ "ipprotocolname": "NETBLT", "ipprotocolnumber": "30", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC969][David_Clark]"}'),
('{ "ipprotocolname": "MFE-NSP", "ipprotocolnumber": "31", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[Shuttleworth  B.  ''A Documentary of MFENet  a National Computer Network''  UCRL-52317  Lawrence Livermore Labs  Livermore  California  June 1977.][Barry_Howard]''"}'),
('{ "ipprotocolname": "MERIT-INP", "ipprotocolnumber": "32", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Hans_Werner_Braun]"}'),
('{ "ipprotocolname": "DCCP", "ipprotocolnumber": "33", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC4340]"}'),
('{ "ipprotocolname": "3PC", "ipprotocolnumber": "34", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Stuart_A_Friedberg]"}'),
('{ "ipprotocolname": "IDPR", "ipprotocolnumber": "35", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Martha_Steenstrup]"}'),
('{ "ipprotocolname": "XTP", "ipprotocolnumber": "36", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Greg_Chesson]"}'),
('{ "ipprotocolname": "DDP", "ipprotocolnumber": "37", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Wesley_Craig]"}'),
('{ "ipprotocolname": "IDPR-CMTP", "ipprotocolnumber": "38", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Martha_Steenstrup]"}'),
('{ "ipprotocolname": "TP++", "ipprotocolnumber": "39", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Dirk_Fromhein]"}'),
('{ "ipprotocolname": "IL", "ipprotocolnumber": "40", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Dave_Presotto]"}'),
('{ "ipprotocolname": "IPv6", "ipprotocolnumber": "41", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2473]"}'),
('{ "ipprotocolname": "SDRP", "ipprotocolnumber": "42", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Deborah_Estrin]"}'),
('{ "ipprotocolname": "IPv6-Route", "ipprotocolnumber": "43", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steve_Deering]"}'),
('{ "ipprotocolname": "IPv6-Frag", "ipprotocolnumber": "44", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steve_Deering]"}'),
('{ "ipprotocolname": "IDRP", "ipprotocolnumber": "45", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Sue_Hares]"}'),
('{ "ipprotocolname": "RSVP", "ipprotocolnumber": "46", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2205][RFC3209][Bob_Braden]"}'),
('{ "ipprotocolname": "GRE", "ipprotocolnumber": "47", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2784][Tony_Li]"}'),
('{ "ipprotocolname": "DSR", "ipprotocolnumber": "48", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC4728]"}'),
('{ "ipprotocolname": "BNA", "ipprotocolnumber": "49", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Gary Salamon]"}'),
('{ "ipprotocolname": "ESP", "ipprotocolnumber": "50", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC4303]"}'),
('{ "ipprotocolname": "AH", "ipprotocolnumber": "51", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC4302]"}'),
('{ "ipprotocolname": "I-NLSP", "ipprotocolnumber": "52", "servicename": "", "portnumber": "", "type": "protocol", "description": "[K_Robert_Glenn]"}'),
('{ "ipprotocolname": "SWIPE (deprecated)", "ipprotocolnumber": "53", "servicename": "", "portnumber": "", "type": "protocol", "description": "[John_Ioannidis]"}'),
('{ "ipprotocolname": "NARP", "ipprotocolnumber": "54", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC1735]"}'),
('{ "ipprotocolname": "MOBILE", "ipprotocolnumber": "55", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Charlie_Perkins]"}'),
('{ "ipprotocolname": "TLSP", "ipprotocolnumber": "56", "servicename": "", "portnumber": "", "type": "protocol", "description": ""}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "using Kryptonet key management", "servicename": "", "portnumber": "", "type": "protocol", "description": ""}'),
('{ "ipprotocolname": "SKIP", "ipprotocolnumber": "57", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Tom_Markson]"}'),
('{ "ipprotocolname": "IPv6-ICMP", "ipprotocolnumber": "58", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2460]"}'),
('{ "ipprotocolname": "IPv6-NoNxt", "ipprotocolnumber": "59", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2460]"}'),
('{ "ipprotocolname": "IPv6-Opts", "ipprotocolnumber": "60", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2460]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "61", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "CFTP", "ipprotocolnumber": "62", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[Forsdick  H.  ''CFTP''  Network Message  Bolt Beranek and Newman  January 1982.][Harry_Forsdick]''"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "63", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "SAT-EXPAK", "ipprotocolnumber": "64", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "KRYPTOLAN", "ipprotocolnumber": "65", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Paul Liu]"}'),
('{ "ipprotocolname": "RVD", "ipprotocolnumber": "66", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Michael_Greenwald]"}'),
('{ "ipprotocolname": "IPPC", "ipprotocolnumber": "67", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "68", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "SAT-MON", "ipprotocolnumber": "69", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "VISA", "ipprotocolnumber": "70", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Gene_Tsudik]"}'),
('{ "ipprotocolname": "IPCV", "ipprotocolnumber": "71", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "CPNX", "ipprotocolnumber": "72", "servicename": "", "portnumber": "", "type": "protocol", "description": "[David Mittnacht]"}'),
('{ "ipprotocolname": "CPHB", "ipprotocolnumber": "73", "servicename": "", "portnumber": "", "type": "protocol", "description": "[David Mittnacht]"}'),
('{ "ipprotocolname": "WSN", "ipprotocolnumber": "74", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Victor Dafoulas]"}'),
('{ "ipprotocolname": "PVP", "ipprotocolnumber": "75", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steve_Casner]"}'),
('{ "ipprotocolname": "BR-SAT-MON", "ipprotocolnumber": "76", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "SUN-ND", "ipprotocolnumber": "77", "servicename": "", "portnumber": "", "type": "protocol", "description": "[William_Melohn]"}'),
('{ "ipprotocolname": "WB-MON", "ipprotocolnumber": "78", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "WB-EXPAK", "ipprotocolnumber": "79", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Steven_Blumenthal]"}'),
('{ "ipprotocolname": "ISO-IP", "ipprotocolnumber": "80", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Marshall_T_Rose]"}'),
('{ "ipprotocolname": "VMTP", "ipprotocolnumber": "81", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Dave_Cheriton]"}'),
('{ "ipprotocolname": "SECURE-VMTP", "ipprotocolnumber": "82", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Dave_Cheriton]"}'),
('{ "ipprotocolname": "VINES", "ipprotocolnumber": "83", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Brian Horn]"}'),
('{ "ipprotocolname": "TTP", "ipprotocolnumber": "84", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Jim_Stevens]"}'),
('{ "ipprotocolname": "IPTM", "ipprotocolnumber": "84", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Jim_Stevens]"}'),
('{ "ipprotocolname": "NSFNET-IGP", "ipprotocolnumber": "85", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Hans_Werner_Braun]"}'),
('{ "ipprotocolname": "DGP", "ipprotocolnumber": "86", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[M/A-COM Government Systems  ''Dissimilar Gateway Protocol Specification  Draft Version''  Contract no. CS901145  November 16  1987.][Mike_Little]''"}'),
('{ "ipprotocolname": "TCF", "ipprotocolnumber": "87", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Guillermo_A_Loyola]"}'),
('{ "ipprotocolname": "EIGRP", "ipprotocolnumber": "88", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC7868]"}'),
('{ "ipprotocolname": "OSPFIGP", "ipprotocolnumber": "89", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC1583][RFC2328][RFC5340][John_Moy]"}'),
('{ "ipprotocolname": "Sprite-RPC", "ipprotocolnumber": "90", "servicename": "", "portnumber": "", "type": "protocol", "description": "''[Welch  B.  ''The Sprite Remote Procedure Call System''  Technical Report  UCB/Computer Science Dept.  86/302  University of California at Berkeley  June 1986.][Bruce Willins]''"}'),
('{ "ipprotocolname": "LARP", "ipprotocolnumber": "91", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Brian Horn]"}'),
('{ "ipprotocolname": "MTP", "ipprotocolnumber": "92", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Susie_Armstrong]"}'),
('{ "ipprotocolname": "AX.25", "ipprotocolnumber": "93", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Brian_Kantor]"}'),
('{ "ipprotocolname": "IPIP", "ipprotocolnumber": "94", "servicename": "", "portnumber": "", "type": "protocol", "description": "[John_Ioannidis]"}'),
('{ "ipprotocolname": "MICP (deprecated)", "ipprotocolnumber": "95", "servicename": "", "portnumber": "", "type": "protocol", "description": "[John_Ioannidis]"}'),
('{ "ipprotocolname": "SCC-SP", "ipprotocolnumber": "96", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Howard_Hart]"}'),
('{ "ipprotocolname": "ETHERIP", "ipprotocolnumber": "97", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC3378]"}'),
('{ "ipprotocolname": "ENCAP", "ipprotocolnumber": "98", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC1241][Robert_Woodburn]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "99", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "GMTP", "ipprotocolnumber": "100", "servicename": "", "portnumber": "", "type": "protocol", "description": "[[RXB5]]"}'),
('{ "ipprotocolname": "IFMP", "ipprotocolnumber": "101", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Bob_Hinden][November 1995  1997.]"}'),
('{ "ipprotocolname": "PNNI", "ipprotocolnumber": "102", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Ross_Callon]"}'),
('{ "ipprotocolname": "PIM", "ipprotocolnumber": "103", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC7761][Dino_Farinacci]"}'),
('{ "ipprotocolname": "ARIS", "ipprotocolnumber": "104", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Nancy_Feldman]"}'),
('{ "ipprotocolname": "SCPS", "ipprotocolnumber": "105", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Robert_Durst]"}'),
('{ "ipprotocolname": "QNX", "ipprotocolnumber": "106", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Michael_Hunter]"}'),
('{ "ipprotocolname": "A/N", "ipprotocolnumber": "107", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Bob_Braden]"}'),
('{ "ipprotocolname": "IPComp", "ipprotocolnumber": "108", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC2393]"}'),
('{ "ipprotocolname": "SNP", "ipprotocolnumber": "109", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Manickam_R_Sridhar]"}'),
('{ "ipprotocolname": "Compaq-Peer", "ipprotocolnumber": "110", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Victor_Volpe]"}'),
('{ "ipprotocolname": "IPX-in-IP", "ipprotocolnumber": "111", "servicename": "", "portnumber": "", "type": "protocol", "description": "[CJ_Lee]"}'),
('{ "ipprotocolname": "VRRP", "ipprotocolnumber": "112", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC5798]"}'),
('{ "ipprotocolname": "PGM", "ipprotocolnumber": "113", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Tony_Speakman]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "114", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "L2TP", "ipprotocolnumber": "115", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC3931][Bernard_Aboba]"}'),
('{ "ipprotocolname": "DDX", "ipprotocolnumber": "116", "servicename": "", "portnumber": "", "type": "protocol", "description": "[John_Worley]"}'),
('{ "ipprotocolname": "IATP", "ipprotocolnumber": "117", "servicename": "", "portnumber": "", "type": "protocol", "description": "[John_Murphy]"}'),
('{ "ipprotocolname": "STP", "ipprotocolnumber": "118", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Jean_Michel_Pittet]"}'),
('{ "ipprotocolname": "SRP", "ipprotocolnumber": "119", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Mark_Hamilton]"}'),
('{ "ipprotocolname": "UTI", "ipprotocolnumber": "120", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Peter_Lothberg]"}'),
('{ "ipprotocolname": "SMP", "ipprotocolnumber": "121", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Leif_Ekblad]"}'),
('{ "ipprotocolname": "SM (deprecated)", "ipprotocolnumber": "122", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Jon_Crowcroft][draft-perlman-simple-multicast]"}'),
('{ "ipprotocolname": "PTP", "ipprotocolnumber": "123", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Michael_Welzl]"}'),
('{ "ipprotocolname": "ISIS over IPv4", "ipprotocolnumber": "124", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Tony_Przygienda]"}'),
('{ "ipprotocolname": "FIRE", "ipprotocolnumber": "125", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Criag_Partridge]"}'),
('{ "ipprotocolname": "CRTP", "ipprotocolnumber": "126", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Robert_Sautter]"}'),
('{ "ipprotocolname": "CRUDP", "ipprotocolnumber": "127", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Robert_Sautter]"}'),
('{ "ipprotocolname": "SSCOPMCE", "ipprotocolnumber": "128", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Kurt_Waber]"}'),
('{ "ipprotocolname": "IPLT", "ipprotocolnumber": "129", "servicename": "", "portnumber": "", "type": "protocol", "description": "[[Hollbach]]"}'),
('{ "ipprotocolname": "SPS", "ipprotocolnumber": "130", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Bill_McIntosh]"}'),
('{ "ipprotocolname": "PIPE", "ipprotocolnumber": "131", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Bernhard_Petri]"}'),
('{ "ipprotocolname": "SCTP", "ipprotocolnumber": "132", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Randall_R_Stewart]"}'),
('{ "ipprotocolname": "FC", "ipprotocolnumber": "133", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Murali_Rajagopal][RFC6172]"}'),
('{ "ipprotocolname": "RSVP-E2E-IGNORE", "ipprotocolnumber": "134", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC3175]"}'),
('{ "ipprotocolname": "Mobility Header", "ipprotocolnumber": "135", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC6275]"}'),
('{ "ipprotocolname": "UDPLite", "ipprotocolnumber": "136", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC3828]"}'),
('{ "ipprotocolname": "MPLS-in-IP", "ipprotocolnumber": "137", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC4023]"}'),
('{ "ipprotocolname": "manet", "ipprotocolnumber": "138", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC5498]"}'),
('{ "ipprotocolname": "HIP", "ipprotocolnumber": "139", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC7401]"}'),
('{ "ipprotocolname": "Shim6", "ipprotocolnumber": "140", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC5533]"}'),
('{ "ipprotocolname": "WESP", "ipprotocolnumber": "141", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC5840]"}'),
('{ "ipprotocolname": "ROHC", "ipprotocolnumber": "142", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC5858]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "143-252", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "253", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC3692]"}'),
('{ "ipprotocolname": "", "ipprotocolnumber": "254", "servicename": "", "portnumber": "", "type": "protocol", "description": "[RFC3692]"}'),
('{ "ipprotocolname": "Reserved", "ipprotocolnumber": "255", "servicename": "", "portnumber": "", "type": "protocol", "description": "[Internet_Assigned_Numbers_Authority]"}');
